database_config:
  root_path: ./test_data/
  sqlalchemy_url: sqlite:///test_data/example.db
  echo: false
  optimize_codestate_ids: true
  indexed_columns:
  # Useful for the instructor view
  - AssignmentID
  # Also useful for getting event counts on a file
  - SubjectID
  - CodeStateSection
  - DestinationCodeStateSection
  # Useful for checking session syncing
  - SessionID

  metadata:
    Version: "1.0"
    IsEventOrderingConsistent: true
    EventOrderScope: Restricted
    EventOrderScopeColumns: SessionID
    CodeStateRepresentation: Table
    ProgramInputLinkTable: ""

add_server_timestamps: true
